// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://euxopgmbhjcjbaxmlfrp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1eG9wZ21iaGpjamJheG1sZnJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExMDk0MjcsImV4cCI6MjA1NjY4NTQyN30.xErPVNq2qOtUk34QJ_OWJIpNeGZvrcxKsnKO6ljvtKc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);